# Generated by Django 6.0.3 on 2026-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, help_text="Укажите номер телефона", max_length=11, null=True, verbose_name="Телефон"
            ),
        ),
    ]
