# Generated by Django 6.0.3 on 2026-04-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpost",
            name="ispublic",
            field=models.BooleanField(default=False, verbose_name="статус"),
        ),
    ]
