# Generated by Django 6.0.3 on 2026-04-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_productpost_ispublic"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpost",
            name="view_counter",
            field=models.PositiveIntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
    ]
